### ISSUE TITLE
Hearthstone-Deck-Tracker: Decks with Baron Rivendare

### ISSUE THREAD

**Issue by dvide** [HearthStats/hearthstats#462]
Decks uploaded with Baron Rivendare (using HDT) cause the deck page on HearthStats to 404. A few weeks ago I could see the deck page, but Rivendare was missing from the list of cards. When you do a resync, it sometimes redownloads the deck without Baron Rivendare, meaning the deck in HDT has 29/30 cards. Not sure if this is a server-side or client-side issue, but from what I can tell the client is sending the correct card ID: `FP1_031`. The logs show the server returns success after uploading.

URLs to two decks I have with Rivendare in them, and my profile:
http://hearthstats.net/decks/feign-death-hunter-m?locale=en (Feign Death Hunter [M])
http://hearthstats.net/decks/flood-mage-rivendare?locale=en (Flood Mage =Rivendare=)
http://hearthstats.net/profiles/83926?locale=en

Thanks!

**Comment by trigun0x2** [comment]
Fixed!

**Comment by dvide** [comment]
That was fast! The deck pages are still showing a 404 to me though. Should I try reuploading them? Or will I need to wait a while to see the fix?

**Comment by trigun0x2** [comment]
Oh really. Maybe not fixed yet then. Please give me an hour or two and I'll
get it done :)

**Comment by dvide** [comment]
Ok :+1: no hurry.

**Comment by trigun0x2** [comment]
@dvide actually fixed now :)

**Comment by dvide** [comment]
Confirmed :) thanks!
